name: Docker on Windows
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: Start-Process -FilePath "C:\Program Files\Docker\Docker\DockerCLI.exe" -ArgumentList "-SwitchLinuxEngine"
    - uses: actions/checkout@v2
    - name: Build Docker containers
      run: docker build -t sitespeedio/sitespeed.io .
      shell: cmd
    - name: Run test on default container for Chrome 
      run: docker run --rm sitespeedio/sitespeed.io https://www.sitespeed.io -n 1 -b chrome
      shell: cmd